name: redeploy-payment

on:
  push:
    # watch for push event in main branch
    branches:
      - main

    # watch for changes in specific file
    paths:
      - "trigger.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # build an image
      - run: cd payment && docker build -t thasup/payment .

      # login on docker hub
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # push an image to docker hub
      - run: docker push thasup/payment

      # use and cliententicate doctl
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_2 }}

      # give credential to k8s cluster
      - run: doctl kubernetes cluster kubeconfig save do-covid-cluster

      # restart deployment
      - run: kubectl rollout restart deployment payment-depl
