name: tests-product

on:
  pull_request:
    paths:
      - "product/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd product && npm install && npm run test:ci
