name: tests-product

on:
  pull_request:
    paths:
      - "product/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd product && npm install && npm run test:ci
