name: Greeting Action
on:
  workflow_dispatch:
    inputs:
      name:
        default: "Octocat"
        description: "Name to greet"
      environment:
        type: environment
        required: true
        default: "staging"
  push:
    # watch for pull request into staging branch
    branches:
      - staging
    # watch for changes in folders
    paths:
      - "client/**"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}"
      - run: echo "Hello ${{ github.event.inputs.environment }}"
